### ISSUE TITLE
Filter api/models during generation

### ISSUE THREAD

**Issue by margarita-v** [surfstudio/SurfGen#56]
It would be useful to filter api methods, for example to list the desired api methods for generation via additional config or parameters in command line separated with comma.

Motivation:
1. This feature would be helpful for existed projects for changing the updated methods only
2. This feature would help to avoid errors and to generate only those methods which can be generated successfully. The flexible configuration of generation could be possible.
3. This feature would be helpful for projects with a single swagger api file in order to generate separate services for each particular case

**Comment by chausovSurfStudio** [comment]
+1, when one of N methods in file have [body with binary](https://github.com/surfstudio/SurfGen/issues/40) (or multipart) - only way is moved this method in separate file, which will be exclude from linting. And it's uncomfortable and sad :(

**Comment by margarita-v** [comment]
Yes, two options could be possible:
1. Exclude some models, as described here https://github.com/surfstudio/SurfGen/issues/57, so user can list particular model names which should not be parsed, the warning could be useful too: "SurfGen has skipped the model $modelName". For models which use the skipped one could be possible to replace its links to the skipped model in order to use the stub name. For example, Product has a ProductCategory field, but ProductCategory is skipped and won't be parsed, so the product's field could be `category: TODO` instead of using the name of skipped category (it also depends on template). Probably an additional field for model type could be useful as a sign of a skipped model.
2. Exclude particular api methods and don't analyze them. For example, an api file has logout and login endpoints, but user wants to generate logout and ignore login endpoint.
