### ISSUE TITLE
Provide linux and macOS binary

### ISSUE THREAD

**Issue by margarita-v** [surfstudio/SurfGen#74]
It would be great to add github flow which updates at least two kinds of binary file for Linux and macOS users after pushing into master.
Additional workflow for the same process would be useful for each release of SurfGen.
After such improvements it would be easier to use SurfGen and no one would be required to build from source (could be helpful in this case too https://github.com/surfstudio/SurfGen/issues/73). Also it would be easier to contribute, since the flow will update the binary automatically, and the most actual binary file will be stored in the main branch, so it will make updates easier for current users of SurfGen.

**Comment by LastSprint** [comment]
Look at 2.0.0 release
